name: Pipeline

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ feature/gas-optimization ]
  pull_request:
    branches: [ feature/gas-optimization ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Lint & Test
    runs-on: ubuntu-18.04

    env:
      TEST_BSC_PROVIDER: https://bsc-dataseed.binance.org/
      TEST_ORACLE_KEYS: ${{ secrets.TEST_ORACLE_KEYS}}

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14 LTS
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Installing dependencies
      run: yarn install --frozen-lockfile

    - name: test
      run: yarn start-ganache -q & yarn test
